### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by msjyoo** [SOF3/Basin#1]
GPL is a viral license that stands contradictory to the true values of open source development. Using an MIT license would allow for-profit organisations to use the codebase, which almost all multi-server gameservers are.

**Comment by PEMapModder** [comment]
I just used the PocketMine one o.O

**Comment by PEMapModder** [comment]
http://choosealicense.com/licenses/#lgpl-v3

**Comment by SOF3** [comment]
4da65f0
